@baseUri = http://localhost:3001/api

### generate beauty
POST {{baseUri}}/generate-beauty
Content-Type: application/json

{
  "description": "sydney sweedney"
}

### get beauties
GET {{baseUri}}/get-beauties